services:
  chat-backend:
    image: node:20.19
    working_dir: /workspace/chatapp
    command: >-
      bash -lc "npm install && \
      (cd ../metersapp/apps/meters-mcp && npm install) && \
      (cd ../EmployeeApp/apps/employee-mcp && npm install) && \
      (cd ../FinCostApp/apps/fincost-mcp && npm install) && \
      (cd ../gardenknowledge/apps/garden-mcp && npm install) && \
      (cd ../posbistroapi && npm install) && \
      (cd ../keycloak-mcp && npm install) && \
      npm run dev --workspace backend"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-dummy}
      LLM_MODEL: ${LLM_MODEL:-gpt-5}
      LLM_MODELS: ${LLM_MODELS:-gpt-5,gpt-5-mini,gpt-5-nano,gpt-4o-mini,gpt-4.1-mini}
      ALLOWED_IPS: ${ALLOWED_IPS:-192.168.2.145,192.168.4.170}
    volumes:
      - ..:/workspace:cached
    ports:
      - '4025:4025'
    tty: true
    stdin_open: true

  chat-frontend:
    image: node:20.19
    working_dir: /workspace/chatapp
    command: >-
      bash -lc "npm install && npm run dev --workspace frontend"
    environment:
      VITE_CHATAPI_URL: ${VITE_CHATAPI_URL:-http://192.168.14.55:4025}
    volumes:
      - ..:/workspace:cached
    ports:
      - '4225:4225'
    depends_on:
      - chat-backend
    tty: true
    stdin_open: true
